import type { SimpleIcon } from "simple-icons"
import {
  siAirtable,
  siCalendly,
  siFacebook,
  siGmail,
  siGoogleads,
  siGooglecalendar,
  siGoogleforms,
  siGoogledrive,
  siGooglesheets,
  siHubspot,
  siMailchimp,
  siNotion,
  siPaypal,
  siQuickbooks,
  siSquare,
  siStripe,
  siTypeform,
  siZoho,
} from "simple-icons"

export type IntegrationStatus = "in-use" | "next" | "planned"
export type IntegrationAuth = "oauth" | "api-key" | "webhook" | "managed"

export type IntegrationDefinition = {
  slug: string
  name: string
  category: string
  description: string
  fit: string
  status: IntegrationStatus
  statusLabel: string
  auth: IntegrationAuth
  authLabel: string
  logo: { type: "simple"; icon: SimpleIcon } | { type: "remote"; src: string; source: string }
  website: string
  workflows: Array<{ title: string; description: string }>
  triggers: string[]
  actions: string[]
  setup: string[]
  related: string[]
}

const remoteLogo = (src: string, source: string): IntegrationDefinition["logo"] => ({
  type: "remote",
  src,
  source,
})

const faviconLogo = (domain: string, source: string): IntegrationDefinition["logo"] =>
  remoteLogo(`https://www.google.com/s2/favicons?domain=${domain}&sz=128`, source)

const simpleLogo = (icon: SimpleIcon): IntegrationDefinition["logo"] => ({ type: "simple", icon })

export const integrationCategories = [
  "All apps",
  "Communication",
  "Calendar and booking",
  "CRM and sales",
  "Payments and accounting",
  "Forms and data",
  "Marketing and leads",
  "Files and productivity",
  "Service operations",
  "Limo and dispatch",
] as const

export const integrationCatalog = [
  {
    slug: "gmail",
    name: "Gmail",
    category: "Communication",
    description: "Turn customer email into structured conversations, alerts, and follow-up tasks.",
    fit: "Best for teams already working from a Google Workspace inbox.",
    status: "next",
    statusLabel: "Next connector",
    auth: "oauth",
    authLabel: "Google OAuth",
    logo: simpleLogo(siGmail),
    website: "https://workspace.google.com/products/gmail/",
    workflows: [
      { title: "New inquiry to lead", description: "Extract a customer request from an email and create a lead for the right team." },
      { title: "Booking update to inbox", description: "Send a clear confirmation email after a quote or dispatch event changes." },
    ],
    triggers: ["New message", "New attachment", "Message label changed"],
    actions: ["Send email", "Create draft", "Add label", "Find thread"],
    setup: ["Google Workspace admin approval", "Choose the mailbox Volimox may access", "Review read and send permissions"],
    related: ["Google Calendar", "HubSpot", "Google Sheets"],
  },
  {
    slug: "microsoft-outlook",
    name: "Microsoft Outlook",
    category: "Communication",
    description: "Keep email, contacts, and customer follow-up inside Microsoft 365.",
    fit: "Best for Microsoft 365 teams and operations desks.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Microsoft OAuth",
    logo: faviconLogo("outlook.com", "https://outlook.office.com/"),
    website: "https://www.microsoft.com/microsoft-365/outlook/outlook-business",
    workflows: [
      { title: "Email to dispatch task", description: "Convert a customer email into a reviewable operations task." },
      { title: "Status update to customer", description: "Send a controlled email when a ride, visit, or callback changes state." },
    ],
    triggers: ["New email", "New contact", "New calendar event"],
    actions: ["Send email", "Create draft", "Create contact", "Create calendar event"],
    setup: ["Microsoft Entra admin consent", "Select the Microsoft 365 mailbox", "Choose calendar and mail scopes"],
    related: ["Microsoft Teams", "Microsoft Outlook Calendar", "Salesforce"],
  },
  {
    slug: "slack",
    name: "Slack",
    category: "Communication",
    description: "Route qualified leads, exceptions, and customer updates to the right operations channel.",
    fit: "Best for teams that coordinate work in channels instead of shared inboxes.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Slack OAuth",
    logo: faviconLogo("slack.com", "https://slack.com/"),
    website: "https://slack.com/intl/en-us/features",
    workflows: [
      { title: "High-intent lead alert", description: "Post a structured lead summary to a private sales or dispatch channel." },
      { title: "Exception escalation", description: "Notify a manager when a workflow needs human review." },
    ],
    triggers: ["New channel message", "Reaction added", "New channel"],
    actions: ["Send channel message", "Send direct message", "Create channel", "Add reaction"],
    setup: ["Select a Slack workspace", "Choose allowed channels", "Review message and member scopes"],
    related: ["Gmail", "HubSpot", "Google Calendar"],
  },
  {
    slug: "microsoft-teams",
    name: "Microsoft Teams",
    category: "Communication",
    description: "Deliver operational alerts and customer handoffs into Microsoft 365 team spaces.",
    fit: "Best for larger organizations using Teams for daily coordination.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Microsoft OAuth",
    logo: faviconLogo("teams.microsoft.com", "https://www.microsoft.com/microsoft-teams/"),
    website: "https://www.microsoft.com/microsoft-teams/group-chat-software",
    workflows: [
      { title: "New lead to team", description: "Post a lead card to the selected team and channel." },
      { title: "Missed call escalation", description: "Notify the on-call team when a text-back workflow needs help." },
    ],
    triggers: ["New channel message", "New team member", "New channel"],
    actions: ["Send channel message", "Create channel", "Add team member"],
    setup: ["Microsoft Entra admin consent", "Choose team and channel scope", "Review delegated permissions"],
    related: ["Microsoft Outlook", "Microsoft Outlook Calendar", "ServiceTitan"],
  },
  {
    slug: "twilio",
    name: "Twilio",
    category: "Communication",
    description: "Recover missed calls with text-back messages, call status, replies, and follow-up steps.",
    fit: "Best for businesses where one missed call can become a lost job.",
    status: "in-use",
    statusLabel: "Used in Volimox demos",
    auth: "managed",
    authLabel: "Managed connection",
    logo: faviconLogo("twilio.com", "https://www.twilio.com/"),
    website: "https://www.twilio.com/messaging",
    workflows: [
      { title: "Missed call to text-back", description: "Send a clear SMS after a missed call and capture the customer’s need." },
      { title: "Reply to prepared lead", description: "Attach inbound replies to the same conversation and lead record." },
    ],
    triggers: ["Missed call", "Inbound SMS", "Call status changed", "Message status changed"],
    actions: ["Send SMS", "Start call", "Read message status", "Schedule follow-up"],
    setup: ["Verified Twilio account", "Dedicated phone number or messaging service", "Messaging and voice consent review"],
    related: ["Google Sheets", "HubSpot", "Slack"],
  },
  {
    slug: "ringcentral",
    name: "RingCentral",
    category: "Communication",
    description: "Connect business calling and messaging events to customer intake and follow-up.",
    fit: "Best for teams already using RingCentral as their phone system.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "RingCentral OAuth",
    logo: faviconLogo("ringcentral.com", "https://www.ringcentral.com/"),
    website: "https://www.ringcentral.com/office/features.html",
    workflows: [
      { title: "Call outcome to lead", description: "Use a completed call event to create or update a customer record." },
      { title: "Voicemail to review queue", description: "Route voicemail metadata to the right team for follow-up." },
    ],
    triggers: ["Call ended", "Voicemail received", "SMS received"],
    actions: ["Send SMS", "Start call", "Create contact"],
    setup: ["RingCentral admin approval", "Choose the phone numbers", "Review call and message scopes"],
    related: ["HubSpot", "Salesforce", "Google Calendar"],
  },
  {
    slug: "google-calendar",
    name: "Google Calendar",
    category: "Calendar and booking",
    description: "Turn customer requests into availability checks, confirmed events, and reminders.",
    fit: "Best for teams scheduling rides, visits, callbacks, or consultations.",
    status: "next",
    statusLabel: "Next connector",
    auth: "oauth",
    authLabel: "Google OAuth",
    logo: simpleLogo(siGooglecalendar),
    website: "https://workspace.google.com/products/calendar/",
    workflows: [
      { title: "Qualified lead to calendar hold", description: "Create a reviewable hold after the required booking details are collected." },
      { title: "Calendar event to customer update", description: "Send a confirmation or reminder when the event becomes ready." },
    ],
    triggers: ["Event created", "Event updated", "Event starts soon"],
    actions: ["Find availability", "Create event", "Update event", "Cancel event"],
    setup: ["Choose one or more calendars", "Set timezone and working hours", "Review event read/write scope"],
    related: ["Gmail", "Calendly", "HubSpot"],
  },
  {
    slug: "microsoft-outlook-calendar",
    name: "Microsoft Outlook Calendar",
    category: "Calendar and booking",
    description: "Coordinate appointments and dispatch windows across Microsoft 365 calendars.",
    fit: "Best for organizations scheduling in Outlook rather than Google Calendar.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Microsoft OAuth",
    logo: faviconLogo("outlook.com", "https://outlook.office.com/"),
    website: "https://www.microsoft.com/microsoft-365/outlook/outlook-business",
    workflows: [
      { title: "Request to calendar hold", description: "Create a tentative event after a customer request passes the configured rules." },
      { title: "Schedule change to notification", description: "Send an updated customer message when the assigned time moves." },
    ],
    triggers: ["Event created", "Event updated", "Event canceled"],
    actions: ["Find availability", "Create event", "Update event", "Cancel event"],
    setup: ["Microsoft Entra admin consent", "Select calendars", "Set timezone and working hours"],
    related: ["Microsoft Outlook", "Microsoft Teams", "HubSpot"],
  },
  {
    slug: "calendly",
    name: "Calendly",
    category: "Calendar and booking",
    description: "Convert a qualified conversation into a customer-selected meeting or callback slot.",
    fit: "Best for teams that let customers book without email back-and-forth.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Calendly OAuth",
    logo: simpleLogo(siCalendly),
    website: "https://calendly.com/",
    workflows: [
      { title: "Lead to booking link", description: "Send the right scheduling link after the lead meets the configured criteria." },
      { title: "Booking to customer record", description: "Attach the scheduled event and invitee details to the conversation." },
    ],
    triggers: ["Invitee created", "Invitee canceled", "Event scheduled"],
    actions: ["Create scheduling link", "Find event", "Cancel event"],
    setup: ["Choose event types", "Select the owner or team", "Review invitee data scope"],
    related: ["Google Calendar", "HubSpot", "Gmail"],
  },
  {
    slug: "acuity-scheduling",
    name: "Acuity Scheduling",
    category: "Calendar and booking",
    description: "Collect appointment details, payments, and intake forms before a scheduled service.",
    fit: "Best for service businesses using Acuity’s booking and intake flow.",
    status: "planned",
    statusLabel: "Planned",
    auth: "api-key",
    authLabel: "Scoped API token",
    logo: faviconLogo("acuityscheduling.com", "https://acuityscheduling.com/"),
    website: "https://www.squarespace.com/scheduling",
    workflows: [
      { title: "Appointment to lead", description: "Create a structured lead when a new appointment is booked." },
      { title: "Canceled appointment to follow-up", description: "Route cancellations into a recovery sequence for the team." },
    ],
    triggers: ["Appointment booked", "Appointment canceled", "Appointment rescheduled"],
    actions: ["Create appointment", "Update appointment", "Find appointment"],
    setup: ["Acuity administrator token", "Select appointment calendars", "Confirm customer-data scope"],
    related: ["Google Calendar", "Stripe", "Mailchimp"],
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    category: "CRM and sales",
    description: "Move qualified conversations into leads, contacts, opportunities, and accountable follow-up.",
    fit: "Best for enterprise teams with a governed Salesforce pipeline.",
    status: "next",
    statusLabel: "Next connector",
    auth: "oauth",
    authLabel: "Salesforce OAuth",
    logo: faviconLogo("salesforce.com", "https://www.salesforce.com/"),
    website: "https://www.salesforce.com/",
    workflows: [
      { title: "Qualified inquiry to lead", description: "Create a lead only after the configured required fields are present." },
      { title: "Opportunity stage to customer update", description: "Send a controlled message when a sales stage changes." },
    ],
    triggers: ["New lead", "New contact", "Record updated", "New opportunity"],
    actions: ["Create lead", "Create contact", "Create opportunity", "Update record"],
    setup: ["Salesforce administrator approval", "Select objects and fields", "Review least-privilege scopes"],
    related: ["Gmail", "Slack", "QuickBooks Online"],
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    category: "CRM and sales",
    description: "Capture inbound demand, route ownership, and keep customer context attached to the conversation.",
    fit: "Best for growing teams that want CRM, marketing, and sales in one workspace.",
    status: "next",
    statusLabel: "Next connector",
    auth: "oauth",
    authLabel: "HubSpot OAuth",
    logo: simpleLogo(siHubspot),
    website: "https://www.hubspot.com/products/crm",
    workflows: [
      { title: "Form or call to contact", description: "Create or update a contact and preserve the original request." },
      { title: "Lead owner to team alert", description: "Notify the assigned team when a lead reaches a configured priority." },
    ],
    triggers: ["New contact", "New deal", "Contact property changed", "Form submission"],
    actions: ["Create contact", "Create deal", "Update contact", "Create task"],
    setup: ["Choose a HubSpot account", "Select pipelines and owners", "Review contact and CRM scopes"],
    related: ["Gmail", "Calendly", "Slack"],
  },
  {
    slug: "highlevel",
    name: "HighLevel",
    category: "CRM and sales",
    description: "Connect lead capture, conversations, pipelines, and follow-up inside one agency workspace.",
    fit: "Best for agencies and multi-location operators using HighLevel.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "HighLevel OAuth",
    logo: faviconLogo("gohighlevel.com", "https://www.gohighlevel.com/"),
    website: "https://www.gohighlevel.com/",
    workflows: [
      { title: "Inbound lead to opportunity", description: "Create or update a pipeline opportunity from a structured customer request." },
      { title: "Missed call to nurture", description: "Start a controlled follow-up path after a missed call event." },
    ],
    triggers: ["Contact created", "Opportunity created", "Inbound message", "Appointment booked"],
    actions: ["Create contact", "Create opportunity", "Add tag", "Send message"],
    setup: ["Agency or location authorization", "Choose pipeline and stage", "Review contact and messaging scopes"],
    related: ["Twilio", "Calendly", "Stripe"],
  },
  {
    slug: "zoho-crm",
    name: "Zoho CRM",
    category: "CRM and sales",
    description: "Keep lead, contact, account, and deal records synchronized with customer conversations.",
    fit: "Best for small and mid-sized teams on the Zoho stack.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Zoho OAuth",
    logo: simpleLogo(siZoho),
    website: "https://www.zoho.com/crm/",
    workflows: [
      { title: "New request to lead", description: "Create a lead with a source and conversation summary." },
      { title: "Deal update to customer message", description: "Send an approved update when the deal reaches a configured stage." },
    ],
    triggers: ["New lead", "New contact", "Record updated", "New deal"],
    actions: ["Create lead", "Create contact", "Create deal", "Update record"],
    setup: ["Choose Zoho region", "Select modules and fields", "Review CRM scopes"],
    related: ["Gmail", "Google Sheets", "Mailchimp"],
  },
  {
    slug: "pipedrive",
    name: "Pipedrive",
    category: "CRM and sales",
    description: "Turn conversations into visible pipeline stages and next actions for sales teams.",
    fit: "Best for sales teams that run on a simple deal pipeline.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Pipedrive OAuth",
    logo: faviconLogo("pipedrive.com", "https://www.pipedrive.com/"),
    website: "https://www.pipedrive.com/",
    workflows: [
      { title: "Qualified lead to deal", description: "Create a deal and assign it to the correct pipeline stage." },
      { title: "Deal stage to task", description: "Create the next follow-up task when a deal moves forward." },
    ],
    triggers: ["New person", "New organization", "New deal", "Deal stage changed"],
    actions: ["Create person", "Create deal", "Update deal", "Create activity"],
    setup: ["Choose a Pipedrive account", "Select pipeline and stages", "Review person and deal scopes"],
    related: ["Gmail", "Calendly", "Google Sheets"],
  },
  {
    slug: "stripe",
    name: "Stripe",
    category: "Payments and accounting",
    description: "Connect approved payment events to customer records, receipts, and operational follow-up.",
    fit: "Best for online deposits, payment links, and card-based service workflows.",
    status: "next",
    statusLabel: "Next connector",
    auth: "oauth",
    authLabel: "Stripe OAuth",
    logo: simpleLogo(siStripe),
    website: "https://stripe.com/",
    workflows: [
      { title: "Approved quote to payment link", description: "Create a payment request only after the required quote state is confirmed." },
      { title: "Payment to customer update", description: "Attach a verified payment event to the right customer and booking." },
    ],
    triggers: ["Payment succeeded", "Checkout completed", "Refund created", "Invoice paid"],
    actions: ["Create payment link", "Create customer", "Create invoice", "Read payment status"],
    setup: ["Stripe account owner approval", "Select connected account", "Review payment and customer scopes"],
    related: ["QuickBooks Online", "HubSpot", "Google Calendar"],
  },
  {
    slug: "square",
    name: "Square",
    category: "Payments and accounting",
    description: "Connect in-person and online payment events to customer and service workflows.",
    fit: "Best for operators already taking payments through Square.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Square OAuth",
    logo: simpleLogo(siSquare),
    website: "https://squareup.com/us/en",
    workflows: [
      { title: "Payment to customer record", description: "Update a customer record after a verified Square payment." },
      { title: "Refund to team review", description: "Route a refund event to the selected operations channel." },
    ],
    triggers: ["Payment completed", "Refund created", "Customer created"],
    actions: ["Create payment link", "Create customer", "Read payment status"],
    setup: ["Choose Square location", "Select payments and customer scopes", "Verify webhook endpoint"],
    related: ["QuickBooks Online", "Mailchimp", "Google Sheets"],
  },
  {
    slug: "quickbooks-online",
    name: "QuickBooks Online",
    category: "Payments and accounting",
    description: "Carry completed work into invoices, customers, receipts, and finance follow-up.",
    fit: "Best for service businesses that run bookkeeping through Intuit.",
    status: "next",
    statusLabel: "Next connector",
    auth: "oauth",
    authLabel: "Intuit OAuth",
    logo: simpleLogo(siQuickbooks),
    website: "https://quickbooks.intuit.com/",
    workflows: [
      { title: "Completed job to invoice", description: "Create a reviewable invoice from an approved service record." },
      { title: "Payment to lead record", description: "Mark the related customer or booking as paid after confirmation." },
    ],
    triggers: ["Invoice created", "Payment received", "Customer created", "Estimate accepted"],
    actions: ["Create customer", "Create invoice", "Create estimate", "Record payment"],
    setup: ["Choose a QuickBooks company", "Map products and tax codes", "Review accounting scopes"],
    related: ["Stripe", "Square", "HubSpot"],
  },
  {
    slug: "paypal",
    name: "PayPal",
    category: "Payments and accounting",
    description: "Attach verified PayPal payment events to customer and follow-up workflows.",
    fit: "Best for businesses that accept PayPal alongside card payments.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "PayPal OAuth",
    logo: simpleLogo(siPaypal),
    website: "https://www.paypal.com/us/business",
    workflows: [
      { title: "Payment completed to confirmation", description: "Send a confirmation only after the payment event is verified." },
      { title: "Refund to finance review", description: "Create an internal review event when a refund is issued." },
    ],
    triggers: ["Payment completed", "Refund issued", "Dispute opened"],
    actions: ["Create invoice", "Read payment status", "Send receipt"],
    setup: ["Choose a PayPal business account", "Review payment scopes", "Verify webhook endpoint"],
    related: ["QuickBooks Online", "HubSpot", "Gmail"],
  },
  {
    slug: "google-sheets",
    name: "Google Sheets",
    category: "Forms and data",
    description: "Keep lightweight operational logs, review queues, and exports connected to the conversation.",
    fit: "Best for teams that still rely on a shared spreadsheet for daily visibility.",
    status: "next",
    statusLabel: "Next connector",
    auth: "oauth",
    authLabel: "Google OAuth",
    logo: simpleLogo(siGooglesheets),
    website: "https://workspace.google.com/products/sheets/",
    workflows: [
      { title: "New lead to review row", description: "Append a structured lead row without losing the original source." },
      { title: "Status change to sheet update", description: "Update the matching row when the workflow reaches a new state." },
    ],
    triggers: ["New row", "Updated row", "New worksheet"],
    actions: ["Append row", "Update row", "Find row", "Create worksheet"],
    setup: ["Choose a Google Drive account", "Select spreadsheet and worksheet", "Review file access scope"],
    related: ["Gmail", "Google Forms", "HubSpot"],
  },
  {
    slug: "airtable",
    name: "Airtable",
    category: "Forms and data",
    description: "Turn conversations into structured records in a flexible operational database.",
    fit: "Best for teams building a lightweight custom operations workspace.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Airtable OAuth",
    logo: simpleLogo(siAirtable),
    website: "https://www.airtable.com/",
    workflows: [
      { title: "Lead to base record", description: "Create a record in the selected base with normalized customer fields." },
      { title: "Record status to notification", description: "Notify a team when an operations record needs attention." },
    ],
    triggers: ["Record created", "Record updated", "Record enters view"],
    actions: ["Create record", "Update record", "Find record", "Add comment"],
    setup: ["Choose a workspace and base", "Map table fields", "Review data access scope"],
    related: ["Slack", "Typeform", "Google Calendar"],
  },
  {
    slug: "google-forms",
    name: "Google Forms",
    category: "Forms and data",
    description: "Bring web form submissions into the same intake and follow-up path as calls and messages.",
    fit: "Best for simple lead forms and internal request forms.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Google OAuth",
    logo: simpleLogo(siGoogleforms),
    website: "https://www.google.com/forms/about/",
    workflows: [
      { title: "Form submission to lead", description: "Normalize form answers into the same lead model as voice and SMS." },
      { title: "Form request to team alert", description: "Route urgent answers to the right operations channel." },
    ],
    triggers: ["New response"],
    actions: ["Create response", "Read response", "Link response sheet"],
    setup: ["Choose the response form", "Map required fields", "Review Drive access scope"],
    related: ["Google Sheets", "Gmail", "Slack"],
  },
  {
    slug: "typeform",
    name: "Typeform",
    category: "Forms and data",
    description: "Use conversational forms to capture richer customer requests before a human handoff.",
    fit: "Best for polished intake forms with branching questions.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Typeform OAuth",
    logo: simpleLogo(siTypeform),
    website: "https://www.typeform.com/",
    workflows: [
      { title: "Completed form to lead", description: "Create a lead from a completed intake with the form source attached." },
      { title: "Urgent answer to escalation", description: "Escalate an answer when it matches the configured urgency rule." },
    ],
    triggers: ["Form submitted", "Form created"],
    actions: ["Create form response", "Find response", "Create webhook"],
    setup: ["Choose forms", "Map answer fields", "Verify webhook signing secret"],
    related: ["HubSpot", "Google Sheets", "Slack"],
  },
  {
    slug: "jotform",
    name: "Jotform",
    category: "Forms and data",
    description: "Capture service requests, signatures, and customer details in a structured form workflow.",
    fit: "Best for teams that need more complex forms and approval steps.",
    status: "planned",
    statusLabel: "Planned",
    auth: "api-key",
    authLabel: "Scoped API key",
    logo: faviconLogo("jotform.com", "https://www.jotform.com/"),
    website: "https://www.jotform.com/",
    workflows: [
      { title: "Submission to prepared lead", description: "Create a lead with uploaded form documents attached for review." },
      { title: "Signed form to operations", description: "Route a completed form into the configured handoff workflow." },
    ],
    triggers: ["New submission", "Submission updated", "Form created"],
    actions: ["Find submission", "Create submission", "Read form"],
    setup: ["Jotform account administrator key", "Choose forms", "Review submission data scope"],
    related: ["Google Sheets", "HubSpot", "QuickBooks Online"],
  },
  {
    slug: "mailchimp",
    name: "Mailchimp",
    category: "Marketing and leads",
    description: "Keep permissioned customer follow-up and marketing audiences aligned with lead status.",
    fit: "Best for teams using email campaigns and audience segments.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Mailchimp OAuth",
    logo: simpleLogo(siMailchimp),
    website: "https://mailchimp.com/",
    workflows: [
      { title: "Qualified lead to audience", description: "Add a consented contact to the correct audience and tag." },
      { title: "Unsubscribe to CRM update", description: "Keep customer marketing preference changes visible to the team." },
    ],
    triggers: ["New subscriber", "Unsubscribe", "Tag added"],
    actions: ["Add subscriber", "Update subscriber", "Add tag", "Remove tag"],
    setup: ["Choose an audience", "Map consent and source fields", "Review marketing permissions"],
    related: ["HubSpot", "Typeform", "Google Sheets"],
  },
  {
    slug: "meta-lead-ads",
    name: "Meta Lead Ads",
    category: "Marketing and leads",
    description: "Move permissioned Facebook and Instagram lead form submissions into a response workflow.",
    fit: "Best for operators buying local lead generation on Meta.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Meta OAuth",
    logo: simpleLogo(siFacebook),
    website: "https://www.facebook.com/business/ads/lead-ads",
    workflows: [
      { title: "Ad lead to first response", description: "Create a structured lead and trigger the approved first-response path." },
      { title: "Lead quality to routing", description: "Send high-intent leads to the right team based on form answers." },
    ],
    triggers: ["New lead", "Lead form submitted"],
    actions: ["Create lead record", "Update lead status", "Add lead note"],
    setup: ["Meta Business admin access", "Choose pages and forms", "Review lead retrieval permissions"],
    related: ["HubSpot", "Salesforce", "Mailchimp"],
  },
  {
    slug: "google-ads",
    name: "Google Ads",
    category: "Marketing and leads",
    description: "Connect campaign-driven inquiries to source tracking and customer follow-up.",
    fit: "Best for teams measuring paid search against qualified jobs and bookings.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Google Ads OAuth",
    logo: simpleLogo(siGoogleads),
    website: "https://ads.google.com/",
    workflows: [
      { title: "Lead source to CRM", description: "Preserve campaign and ad group context when a lead enters Volimox." },
      { title: "Qualified job to conversion", description: "Send approved conversion events back to the selected account." },
    ],
    triggers: ["Lead form submitted", "Conversion recorded"],
    actions: ["Record conversion", "Find campaign", "Update lead source"],
    setup: ["Google Ads manager access", "Choose customer account", "Review conversion and reporting scopes"],
    related: ["HubSpot", "Salesforce", "Google Sheets"],
  },
  {
    slug: "google-drive",
    name: "Google Drive",
    category: "Files and productivity",
    description: "Keep customer documents, photos, and operational files attached to the work they support.",
    fit: "Best for teams already organizing work in Google Drive.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Google OAuth",
    logo: simpleLogo(siGoogledrive),
    website: "https://workspace.google.com/products/drive/",
    workflows: [
      { title: "New lead folder", description: "Create a controlled folder for documents related to a qualified request." },
      { title: "Uploaded file to review", description: "Notify the team when a customer or technician adds a required file." },
    ],
    triggers: ["File created", "File updated", "File moved"],
    actions: ["Create folder", "Upload file", "Move file", "Share file"],
    setup: ["Choose a shared drive or folder", "Set sharing policy", "Review file access scope"],
    related: ["Google Sheets", "Gmail", "Google Calendar"],
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    category: "Files and productivity",
    description: "Connect file handoffs and document collection to the customer conversation.",
    fit: "Best for teams that use Dropbox as their operational file store.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Dropbox OAuth",
    logo: faviconLogo("dropbox.com", "https://www.dropbox.com/"),
    website: "https://www.dropbox.com/business",
    workflows: [
      { title: "New folder for a job", description: "Create a consistent folder structure after a job is approved." },
      { title: "File upload to alert", description: "Notify the team when a required document arrives." },
    ],
    triggers: ["File added", "File updated", "Folder created"],
    actions: ["Create folder", "Upload file", "Move file", "Create shared link"],
    setup: ["Choose the Dropbox account", "Select root folder", "Review file permissions"],
    related: ["HubSpot", "Google Calendar", "Slack"],
  },
  {
    slug: "notion",
    name: "Notion",
    category: "Files and productivity",
    description: "Keep lightweight operating records, playbooks, and handoff notes attached to the workflow.",
    fit: "Best for teams using Notion databases as an operations layer.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Notion OAuth",
    logo: simpleLogo(siNotion),
    website: "https://www.notion.so/product",
    workflows: [
      { title: "Lead to operations page", description: "Create a structured page for a high-value request in the selected database." },
      { title: "Page status to alert", description: "Notify the team when a record needs a human decision." },
    ],
    triggers: ["Page created", "Page updated", "Database item changed"],
    actions: ["Create page", "Update page", "Find database item", "Add comment"],
    setup: ["Share the selected pages with Volimox", "Choose databases", "Review content access"],
    related: ["Slack", "Google Calendar", "Airtable"],
  },
  {
    slug: "jobber",
    name: "Jobber",
    category: "Service operations",
    description: "Connect customer requests to clients, jobs, quotes, and scheduling in a home-service workspace.",
    fit: "Best for plumbing, HVAC, electrical, cleaning, and other local service teams.",
    status: "next",
    statusLabel: "Next connector",
    auth: "oauth",
    authLabel: "Jobber OAuth",
    logo: faviconLogo("getjobber.com", "https://getjobber.com/"),
    website: "https://getjobber.com/",
    workflows: [
      { title: "Customer request to client", description: "Create or update the Jobber client record after intake is complete." },
      { title: "Approved quote to job", description: "Create a reviewable job only after the configured approval step." },
    ],
    triggers: ["Client created", "Quote approved", "Job updated", "Appointment scheduled"],
    actions: ["Create client", "Create request", "Create quote", "Create job"],
    setup: ["Jobber developer app authorization", "Choose required scopes", "Configure webhook endpoint"],
    related: ["Google Calendar", "QuickBooks Online", "Twilio"],
  },
  {
    slug: "servicetitan",
    name: "ServiceTitan",
    category: "Service operations",
    description: "Connect qualified calls and leads to a governed service-business operations platform.",
    fit: "Best for larger HVAC, plumbing, and electrical operators.",
    status: "planned",
    statusLabel: "Partner access required",
    auth: "oauth",
    authLabel: "Partner API credentials",
    logo: faviconLogo("servicetitan.com", "https://www.servicetitan.com/"),
    website: "https://www.servicetitan.com/",
    workflows: [
      { title: "Lead intake to booking queue", description: "Create a reviewable lead with source and conversation context." },
      { title: "Dispatch change to customer update", description: "Send an approved status message when the assigned visit changes." },
    ],
    triggers: ["Lead created", "Appointment updated", "Job status changed"],
    actions: ["Create lead", "Create customer", "Create appointment", "Update job"],
    setup: ["ServiceTitan partner access", "Integration environment", "Tenant and business-unit mapping"],
    related: ["Twilio", "Google Calendar", "QuickBooks Online"],
  },
  {
    slug: "housecall-pro",
    name: "Housecall Pro",
    category: "Service operations",
    description: "Carry calls, forms, and customer requests into a home-service scheduling workflow.",
    fit: "Best for local service businesses using Housecall Pro.",
    status: "planned",
    statusLabel: "Planned",
    auth: "oauth",
    authLabel: "Provider authorization",
    logo: faviconLogo("housecallpro.com", "https://www.housecallpro.com/"),
    website: "https://www.housecallpro.com/",
    workflows: [
      { title: "Missed call to customer", description: "Create a customer or job request after the text-back conversation is complete." },
      { title: "Job status to follow-up", description: "Trigger the next approved customer message from a job status update." },
    ],
    triggers: ["Customer created", "Job created", "Job status changed"],
    actions: ["Create customer", "Create job", "Update job", "Add note"],
    setup: ["Housecall Pro account access", "Confirm API availability", "Map service types and status values"],
    related: ["Twilio", "Google Calendar", "QuickBooks Online"],
  },
  {
    slug: "limo-anywhere",
    name: "Limo Anywhere",
    category: "Limo and dispatch",
    description: "Connect ride inquiries, reservations, dispatch details, and customer follow-up for limousine operators.",
    fit: "Best for operators already managing reservations in Limo Anywhere.",
    status: "planned",
    statusLabel: "Customer API access required",
    auth: "api-key",
    authLabel: "Customer API credentials",
    logo: faviconLogo("limoanywhere.com", "https://www.limoanywhere.com/"),
    website: "https://www.limoanywhere.com/",
    workflows: [
      { title: "Ride request to reservation review", description: "Create a reviewable reservation request after route and passenger details are complete." },
      { title: "Reservation update to SMS", description: "Send a customer update when the reservation reaches an approved state." },
    ],
    triggers: ["Reservation created", "Reservation updated", "Dispatch status changed"],
    actions: ["Create reservation", "Update reservation", "Find customer", "Add note"],
    setup: ["Existing Limo Anywhere customer account", "API license and credentials", "Map vehicle and service types"],
    related: ["Twilio", "Google Calendar", "Stripe"],
  },
  {
    slug: "moovs",
    name: "Moovs",
    category: "Limo and dispatch",
    description: "Bring ground-transportation inquiries and reservation work into the same customer handoff.",
    fit: "Best for operators running reservations and dispatch in Moovs.",
    status: "planned",
    statusLabel: "API review required",
    auth: "oauth",
    authLabel: "Provider authorization",
    logo: faviconLogo("moovs.com", "https://www.moovs.com/"),
    website: "https://www.moovs.com/",
    workflows: [
      { title: "Quote request to reservation", description: "Pass a complete ride request into a reviewable reservation workflow." },
      { title: "Dispatch event to passenger update", description: "Send an approved SMS or email when the ride status changes." },
    ],
    triggers: ["Reservation created", "Reservation updated", "Trip status changed"],
    actions: ["Create reservation", "Update trip", "Find passenger", "Add note"],
    setup: ["Confirm Moovs API access", "Select account and locations", "Map vehicle and trip statuses"],
    related: ["Twilio", "Google Calendar", "Stripe"],
  },
] satisfies IntegrationDefinition[]

export type IntegrationSlug = (typeof integrationCatalog)[number]["slug"]

export const integrationBySlug = new Map(integrationCatalog.map((integration) => [integration.slug, integration]))

export function getIntegration(slug: string) {
  return integrationBySlug.get(slug)
}
